version: '3.8'

services:
  web_app:
    build: ./web_app
    ports:
      - "5000:5000"
    volumes:
      - type: volume
        source: data_volume
        target: /app/data
    networks:
      - homework_network

  thermometer_simulator:
    build: ./thermometer_simulator
    networks:
      - homework_network

volumes:
  data_volume:
    name: big_homework_1_data_volume
    driver: local

networks:
  homework_network:
    name: big_homework_1_network
    driver: bridge
